//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealState.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Favorite = new HashSet<Favorite>();
            this.Image = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public int BedroomNumber { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string NeighboorHood { get; set; }
        public string StreetName { get; set; }
        public int HouseNumber { get; set; }
        public int Area { get; set; }
        public int UserId { get; set; }
        public int Price { get; set; }
        public int GarageSpace { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Image { get; set; }
        public virtual User User { get; set; }
    }
}
